config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: "homes#top"
  get'home/about' => 'homes#about'
  
  resources :books, only: [:destroy,:edit,:update,:create, :index, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:show, :edit,:index,:update]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
   
  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 } 
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :name, uniqueness: true,length: { in: 2..20}  
  validates :introduction,length: { maximum: 50 } 
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/dognut.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :is_matching_login_user, only: [:edit, :update]
  #before_action :is_matching_login_user_book, only: [:edit, :update]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @newbook=Book.new
    @book = Book.find(params[:book_id])
    @user=User.find(@book.user.id)
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.save
    if @book_comment.save
      redirect_to  request.referer
    else
      render 'books/show'
    end

  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @user=User.find(current_user.id)
    @book=Book.new
    @books=Book.all
  end
  
  def create
    @user=User.find(current_user.id)
    @books=Book.all
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @user=User.find(current_user.id)
    @newbook=Book.new
    @book_comment=BookComment.new
    @book=Book.find(params[:id])
    @user=User.find(@book.user.id)
  end
  
  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def edit
    @book=Book.find(params[:id])
  end
  
  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
    @user=User.find(current_user.id)
    @newbook=Book.new
  end
  def show
    @user=User.find(params[:id])
    @newbook=Book.new
    @books=@user.books
  end

  def edit
    @user = User.find(params[:id])
    
  end
  
  def update
    
    @user=User.find(params[:id])
    if(@user.update(user_params))
      flash[:notice] = "User was successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%=user.name%></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th>
      <% if(user.introduction) %>
        <%=user.introduction%>
      <% end %>
    </th>
  </tr>
</table>
<div class="row">
  <%=link_to edit_user_path(user.id) ,class: 'btn btn-outline-secondary btn-block' do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  
</div>

<h2 class="mt-3">New book</h2>

<!-- form_with部分 -->
<%= form_with model: book , method: :post do |f| %>
  <div class="form-group">
    <p>Title</p>
    <%= f.text_field :title ,class: "form-control"%>
  </div>
  <div class="form-group">
    <p>Opinion</p>
    <%= f.text_area :body ,class: "form-control"%>
  </div>

  <div>
    <%= f.submit 'Create Book',class: 'btn btn-success' %>
  </div>
<% end %>
      

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @book do |f| %>
      	<div class="form-group">
      	  <p>Title</p>
      	  <%= f.text_field :title,class:'form-control' %>
      	</div>
      	<div class="form-group">
      	  <p>Opinion</p>
      	  <%= f.text_area :body,class:'form-control' %>
      	</div>
       
      	
      	<div class="form-group">
      	  <%= f.submit 'Update Book',class:" btn btn-success" %>
      	</div>
        
      <% end %>
      <%=link_to 'Show',book_path(@book.id) %> | <%=link_to 'Back',books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
     <%= render 'new', book: @book,user:@user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
        <%@books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100)%>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%=book.body %></td>
          <td>
            <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %> 
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="far fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </p>
            <% end %>
          </td>
          <td>コメント数:<%=book.book_comments.count %></td>
        </tr>
        <% end %>
      </table>
      
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <% if @newbook.errors.any? %>
    <%= @newbook.errors.count %>errors prohibited this book from being saved:
    <ul>
    <% @newbook.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/new', book: @newbook,user:@user %>
      
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>

      <table class="table">
        <tr>
          <td>
            <%=link_to user_path(@book.user) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %>
              <br/><%=@book.user.name%>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%=@book.body %></td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="far fa-heart"></i><%= @book.favorites.count %> 
                <% end %>
              </p>
            <% end %>
          </td>
          <td>コメント数:<%=@book.book_comments.count %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book),class: 'btn btn-success btn-sm' %></td>
          <td><%= link_to "Destroy", book_path(@book),class: 'btn btn-danger btn-sm', method: :delete, "data-confirm" => "Are you sure?" %></td>
          <%end%>
        </tr>

      </table>
     
      <div>
        <% @book.book_comments.each do |book_comment| %>
          <div>
            <%= image_tag book_comment.user.get_profile_image(100,100) %>
            <%= book_comment.comment %>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete ,class: 'btn btn-danger'%>
            <% end %>
          </div>
           <%= link_to book_comment.user.name, user_path(book_comment.user) %>
        <% end %>
        
      </div>
      
      <% if @book_comment.errors.any? %>
        <p><%= @book_comment.errors.count %>errors prohibited this book from being saved:</p>
        <ul>
          <% @book_comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
          <div>
             <%= f.submit "送信" %>
          </div>
        <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice">
    <%= flash[:notice] %>
</p>
<div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to
            <i class="fas fa-book"></i>
            <strong>Bookers</strong>
            </h1>
            <p>
                In
                <i class="fas fa-book"></i>
               <strong> Bookers</strong>,
            </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p> about various books!</p>
            
            <div class="btn-wrapper col-10 mx-auto">
              
                <div class="row">
                  
                  <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                  
                </div>
                <div class="row">
                  <%= link_to 'sign up',new_user_registration_path, class: "btn btn-info btn-sm btn-block mb-3 sign_up" %>
                
                </div>
             </div>
      
        </div>
      </div>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
             <li class="nav-item">
              <%= link_to  user_path(current_user.id), class: 'nav-link text-light' do%>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path ,class: 'nav-link text-light' do%>   
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  books_path ,class: 'nav-link text-light' do%>
                <i class="fas fa-book-open"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do%>
                <i class="fas fa-sign-out-alt"></i>
                log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to  root_path, class: 'nav-link text-light' do%>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to home_about_path, class: 'nav-link text-light'  do%>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do%>
                <i class="fas fa-user-plus"></i>
                sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do%>
                <i class="fas fa-sign-in-alt"></i>
                Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main >
      <p id="notice">
        <%= flash[:notice] %>
      </p>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class='mx-auto'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>User Info</h1>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this book from being saved:
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <p>Name</p>
          <%= f.text_field :name ,class: "form-control"%>
        </div>
        <div class="form-group">
          <p>Image</p>
          <%= f.file_field :profile_image, class: 'form-control',placeholder: "プロフィール画像", accept: "image/*" %>  
        </div>
        <div class="form-group">
          <p>Introduction</p>
          <%= f.text_field :introduction ,class: "form-control"%>
        </div>
        
      	<div class="form-group">
      	  <%= f.submit 'Update User',class:" btn btn-success" %>
      	</div>
        
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/new', book: @newbook,user:@user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>

      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%=link_to('Show',user_path(user.id))%></td>
        </tr>
        <% end %>

      </table>
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/new', book: @newbook,user:@user %>
      
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
        <tr>
          
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100)%>
            <% end %>
          </td>
          <td><%=link_to book.title,book_path(book.id) %></td>
          <td><%= book.body %></td>
          <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"></i><%= book.favorites.count %> 
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="far fa-heart"></i><%= book.favorites.count %>
                <% end %>
              </td>
            <% end %>
          <td>コメント数:<%=book.book_comments.count %></td>
        </tr>
        <% end %>

      </table>
      
    </div>
  </div>
</div>